### ISSUE TITLE
请问stm源码中高维部分的源码如何使用

### ISSUE THREAD

**Issue by chikchikL** [spzhuang/support-tensor-machine#1]
毕设和张量相关，看到您在统计信息论坛公开了stm的源码，想问下拓展到高维的stm如何使用，源码中只是计算了两个变换向量u和v

**Comment by spzhuang** [comment]
我想现在的你应该已经毕业了吧，不好意思，我只是一个平凡的NLP工程师，我自己都没有想到居然有人会关注这个事情，因此直到现在我才看到。以前读研的时候，为了完成结构张量空间模型的论文，为了验证结构张量空间模型效果好坏，而写了高阶支持张量积的代码。时隔多年，很多细节我已经忘记了。高阶支持张量积中的代码（HOSTM）是使用Matlab写的，你可以试试看，在matlab环境中能否运行。如果需要python运行，需要将其改成python版本。支持张量积（二维矩阵情形）有提供python代码，建议参考一下。说实在话，这段代码，是我读研时光中，少数高光时刻。
如果还有需要，可以使用邮件联系我，邮件我几乎天天有所关注。
祝你幸福。
